// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PG332_SoftwareDesign_EksamenH21.Repository;

namespace PG332_SoftwareDesign_EksamenH21.Migrations
{
    [DbContext(typeof(TrackerContext))]
    [Migration("20211109135017_currentSemesterId")]
    partial class currentSemesterId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseCode")
                        .HasColumnType("TEXT");

                    b.Property<float>("CoursePoints")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Lecture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LectureDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.CoursesInSpecialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpecializationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mandatory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("CoursesInSpecializations");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.Specialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.StudentCourseOverview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourseOverviews");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SpecializationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StudentCourseOverviewId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserCoursePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("currentSemesterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("StudentCourseOverviewId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TaskSetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskSetId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.TaskSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LectureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LectureId")
                        .IsUnique();

                    b.ToTable("TaskSets");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Lecture", b =>
                {
                    b.HasOne("PG332_SoftwareDesign_EksamenH21.Course", null)
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.Address", b =>
                {
                    b.HasOne("PG332_SoftwareDesign_EksamenH21.Model.User", null)
                        .WithOne("Address")
                        .HasForeignKey("PG332_SoftwareDesign_EksamenH21.Model.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.CoursesInSpecialization", b =>
                {
                    b.HasOne("PG332_SoftwareDesign_EksamenH21.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PG332_SoftwareDesign_EksamenH21.Model.Specialization", null)
                        .WithMany("CoursesInSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.StudentCourseOverview", b =>
                {
                    b.HasOne("PG332_SoftwareDesign_EksamenH21.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.User", b =>
                {
                    b.HasOne("PG332_SoftwareDesign_EksamenH21.Model.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId");

                    b.HasOne("PG332_SoftwareDesign_EksamenH21.Model.StudentCourseOverview", "StudentCourseOverview")
                        .WithMany()
                        .HasForeignKey("StudentCourseOverviewId");

                    b.Navigation("Specialization");

                    b.Navigation("StudentCourseOverview");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Task", b =>
                {
                    b.HasOne("PG332_SoftwareDesign_EksamenH21.TaskSet", null)
                        .WithMany("Tasks")
                        .HasForeignKey("TaskSetId");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.TaskSet", b =>
                {
                    b.HasOne("PG332_SoftwareDesign_EksamenH21.Lecture", null)
                        .WithOne("TaskSet")
                        .HasForeignKey("PG332_SoftwareDesign_EksamenH21.TaskSet", "LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Course", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Lecture", b =>
                {
                    b.Navigation("TaskSet");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.Specialization", b =>
                {
                    b.Navigation("CoursesInSpecializations");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.Model.User", b =>
                {
                    b.Navigation("Address");
                });

            modelBuilder.Entity("PG332_SoftwareDesign_EksamenH21.TaskSet", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
