@startuml
title Diagram etter planlegging

actor User
participant ProgramController
participant EmailQuestionWrapper
participant PasswordQuestionWrapper
participant UserAuthenticator
participant LoginMessageWrapper
participant OptionsWrapper

participant UserDao
database Database

group Login
	User->ProgramController
	ProgramController->EmailQuestionWrapper
	User<-EmailQuestionWrapper:Ask for email
	User->ProgramController:Enter email
	ProgramController->UserDao:Get user
	UserDao->Database:Get user
	
	alt user exists 
	UserDao<-Database:User data
	ProgramController<-UserDao:UserObject
	ProgramController->PasswordQuestionWrapper
	User<-PasswordQuestionWrapper:Ask for password
	User->ProgramController:Enter password
	ProgramController->PasswordQuestionWrapper
	PasswordQuestionWrapper->UserAuthenticator:Check credentials
	alt Credentials matching
	    ProgramController<-UserAuthenticator:Success
	    ProgramController->LoginMessageWrapper
	    ProgramController<-LoginMessageWrapper:Get menu
	    User<-ProgramController:Show Menu
    else Password's Wrong
    User<-ProgramController:Ask for password	    
	end
	else user doesn't exist 
	    User<-ProgramController:Ask for email
	end
end

group Get task
    User<-ProgramController: Show semester menu
    User->ProgramController: Select semester
    ProgramController->OptionsWrapper:Get course menu
    ProgramController<-OptionsWrapper:Deliver course menu
    User<-ProgramController:Show course menu
    User->ProgramController:Select course 
    ProgramController->OptionsWrapper:Get lecture menu
    ProgramController<-OptionsWrapper: Deliver lecture menu
    User<-ProgramController:Show lecture menu
    User->ProgramController:Select lecture
    ProgramController->OptionsWrapper:Get task menu
    ProgramController<-OptionsWrapper:Deliver task menu
    User<-ProgramController: Show task menu
    User->ProgramController: Select task
    ProgramController->OptionsWrapper:Get task
    ProgramController<-OptionsWrapper:Deliver task
    User<-ProgramController:Show task
    User->ProgramController:Select finished
    ProgramController->OptionsWrapper:Set finished
    User<-ProgramController:Show task finished
    OptionsWrapper->UserDao:Update user
    UserDao->Database:Save changes
end


@enduml